packageExtensions:
  adm-zip@*:
    dependencies:
      original-fs: "*"

plugins:
  - checksum: c6c23088d2a47dbb7b56a8067d6edd8b37ff53a0d970d52a56816f0407194d0be52def9d606ad88df1040ae5c83710d2b9ba4cab8e509b9491811c9ad389e482
    path: .yarn/plugins/@lembdev/plugin-bundle.cjs
    spec: packages/yarn-plugin-bundle/bundles/@lembdev/plugin-bundle.js

yarnPath: .yarn/releases/yarn-4.2.2.cjs
