packageExtensions:
  adm-zip@*:
    dependencies:
      original-fs: '*'

plugins:
  - checksum: c6c23088d2a47dbb7b56a8067d6edd8b37ff53a0d970d52a56816f0407194d0be52def9d606ad88df1040ae5c83710d2b9ba4cab8e509b9491811c9ad389e482
    path: .yarn/plugins/@lembdev/plugin-bundle.cjs
    spec: packages/yarn-plugin-bundle/bundles/@lembdev/plugin-bundle.js
  - checksum: 54036d71faa84d8f296affa01ed4c906d81005c62036fcb7e944f173e0915083459ce97df8e3b890a33fce5317a2ed77d7084e68990fed12b3f0c9ebae8a641c
    path: .yarn/plugins/@yarn.build/plugin-build.cjs
    spec: 'https://yarn.build/latest/build'

yarnPath: .yarn/releases/yarn-4.2.2.cjs
nodeLinker: node-modules
