name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn workspaces foreach --all  build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: .yarn/plugins/@lembdev/plugin-bundle.js

      # Commit new version
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update release version to ${{ github.ref_name }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-release-version
          delete-branch: true
          title: 'release: Update release version to  ${{ github.ref_name }}'
          base: main
          labels: auto-pr
          assignees: lembdev
          reviewers: lembdev
          team-reviewers: |
            owners
            maintainers
          draft: false

permissions:
  contents: write
